// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuI2wkWvAHUcj6mUeQfrQxaMhCCV5_4EI',
    appId: '1:342033325232:web:656c0342a8bcc91bc5ef75',
    messagingSenderId: '342033325232',
    projectId: 'swipe-closet-wayne-v1',
    authDomain: 'swipe-closet-wayne-v1.firebaseapp.com',
    storageBucket: 'swipe-closet-wayne-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXu8YMaRNCDUcjW7C5vXu-ZgUv4H_e3bQ',
    appId: '1:342033325232:android:4a0a68892df4cd5fc5ef75',
    messagingSenderId: '342033325232',
    projectId: 'swipe-closet-wayne-v1',
    storageBucket: 'swipe-closet-wayne-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvnqXK4AwUqD_KrtUkGdoU7E-HQeRDnfI',
    appId: '1:342033325232:ios:efe96fcf3224f84ec5ef75',
    messagingSenderId: '342033325232',
    projectId: 'swipe-closet-wayne-v1',
    storageBucket: 'swipe-closet-wayne-v1.firebasestorage.app',
    iosBundleId: 'com.example.swipeCloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvnqXK4AwUqD_KrtUkGdoU7E-HQeRDnfI',
    appId: '1:342033325232:ios:efe96fcf3224f84ec5ef75',
    messagingSenderId: '342033325232',
    projectId: 'swipe-closet-wayne-v1',
    storageBucket: 'swipe-closet-wayne-v1.firebasestorage.app',
    iosBundleId: 'com.example.swipeCloset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuI2wkWvAHUcj6mUeQfrQxaMhCCV5_4EI',
    appId: '1:342033325232:web:15218d5dfb8d62f0c5ef75',
    messagingSenderId: '342033325232',
    projectId: 'swipe-closet-wayne-v1',
    authDomain: 'swipe-closet-wayne-v1.firebaseapp.com',
    storageBucket: 'swipe-closet-wayne-v1.firebasestorage.app',
  );
}
